# Generated by Django 5.1.6 on 2025-03-18 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalcontent',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='ContentProgress',
        ),
        migrations.DeleteModel(
            name='DigitalContent',
        ),
    ]
